export enum Acsres {
     AUTHENTICATION_WAS_NOT_ATTEMPTED = "N",
     AUTHENTICATION_WAS_ATTEMPTED_CARD_IS_NOT_ESTABLISHED_IN_SYSTEM_OR_BANK_NOT_USE_SYSTEM = "A",
     HOLDER_FULLY_AUTHENTICATED = "A",
     HOLDER_NOT_FULLY_AUTHENTICATED = "D",
     TECHNICAL_PROBLEMS = "E"
}    