import { IBankAccount } from "./bank-account.interface"
import { IFirmAssortmentDiscount } from "./firm-assortment-discount.interface"
import { IFirmCategoryMetadata } from "./firm-category-metadata.interface"
import { IFirmNace } from "./firm-nace.interface"
import { IFirmOffice } from "./firm-office.interface"
import { IFirmPerson } from "./firm-person.interface"
import { IFirmPicture } from "./firm-picture.interface"

/**
 * Firm
 * @description Interface for abra firm
 */
export interface IFirm {
     ID: string,
     ObjVersion: number,
     Rows: IBankAccount [],
     Hidden: boolean,
     Code: string,
     Name: string,
     ResidenceAddress_ID: string,
     OrgIdentNumber: string,
     VATIdentNumber: string,
     EORIIdentNumber: string,
     Firm_ID: string,
     PriceList_ID: string,
     DueTerm: number,
     DueTermForPurchase: number,
     DealerCategory_ID: string,
     DealerDiscount:  number,
     Note: string,
     Credit: number,
     CheckCredit: boolean,
     K0: string,
     K1: string,
     K2: string,
     K3: string,
     K4: string,
     K5: string,
     K6: string,
     K7: string,
     K8: string,
     K9: string,
     K10: string,
     K11: string,
     K12: string,
     K13: string,
     K14: string,
     K15: string,
     WWWAddress: string,
     PenaltyPercent: number,
     FirmOffices: IFirmOffice[],
     FirmNACEs: IFirmNace[],
     CategoriesMetadata: IFirmCategoryMetadata[],
     PaymentType_ID: string,
     TransportationType_ID: string,
     Currency_ID: string,
     Price_ID: string,
     NPTitle: string,
     NPResidencePermitNumber: string,
     NPBirthNumber: string,
     NPSurname: string,
     NPForename: string,
     IsRegistered: boolean,
     RegisterKeptAt: string,
     RegisterFileRef: string,
     RegisterDate$DATE: string,
     PrefillDiscountKind: boolean,
     DealerDiscountKind: number,
     QuantityDiscountKind: number,
     CommunicationType_ID: string,
     AssortmentDiscounts: IFirmAssortmentDiscount[],
     TAXIdentNumber: string,
     Pictures: IFirmPicture[],
     CRMMenuItem_ID: string,
     EInvoiceFormat: number,
     InvoicingDelivery: number,
     ElectronicAddress_ID: string,
     ElecPosAgreementRef: string,
     ImportDataFromARESAt$DATE: string,
     StateConsolidationUnit: boolean,
     LegalPerson: boolean,
     VATPayor: boolean,
     ECDCustomerIdType: number,
     GDPRValiditySuspended: boolean,
     DebitAccount_ID: string,
     CreditAccount_ID: string,
     ScontoUsage: number,
     ScontoPayLimit: number,
     ScontoPattern_ID: string,
     ScontoType_ID: string,
     Picture_ID: string,
     Store_ID: string,
     VATCountry_ID: string,
     AfterDueTerm: number,
     AfterDueTermEnabled: boolean,
     EquityCapital_ID: string,
     Turnover_ID: string,
     Profit_ID: string,
     EmployeeCount_ID: string,
     LegalStatus_ID: string,
     OwnershipType_ID: string,
     CommercialsAgreement: number,
     MainNACECode_ID: string,
     FirmPersons: IFirmPerson[],
     CreatedAt$DATE: string,
     CorrectedAt$DATE: string,
     CreatedBy_ID: string,
     CorrectedBy_ID: string
}